/***********************
    学号：1510122557
    姓名：陈昇辉
***********************/

/**********************
一、建库
**********************/

--切换到主数据库
USE master;
GO

CREATE DATABASE SPJ
ON
PRIMARY
	(NAME=SPJ,
	FILENAME='C:\SQLserver\data\spj\spjdata.mdf',
	SIZE=100MB,
	MAXSIZE=200,
	FILEGROWTH=20)
LOG ON
	(NAME=SPJLOG,
	FILENAME='C:\SQLserver\data\spj\spjlog.ldf',
	SIZE=100MB,
	MAXSIZE=200,
	FILEGROWTH=20);
	GO
USE SPJ
GO
/*********************
二、建表
*********************/
--S表
CREATE TABLE S(
	SNO CHAR(4) PRIMARY KEY,
	SNAME CHAR(10) NOT NULL,
	STATUS SMALLINT NOT NULL,
	CITY CHAR(10) NOT NULL
);
GO
--P表
CREATE TABLE P(
	PNO CHAR(4) PRIMARY KEY,
	PNAME CHAR(10) NOT NULL,
	COLOR CHAR(2) NOT NULL,
	WEIGHT SMALLINT NOT NULL
);
GO
--J表
CREATE TABLE J(
	JNO CHAR(4) PRIMARY KEY,
	JNAME CHAR(10) NOT NULL,
	CITY CHAR(10) NOT NULL
);
GO
--SPJ表
CREATE TABLE SPJ(
	SNO CHAR(4),
	PNO CHAR(4),
	JNO CHAR(4),
	QTY SMALLINT NOT NULL,
	FOREIGN KEY (SNO) REFERENCES S(SNO),
	FOREIGN KEY (PNO) REFERENCES P(PNO),
	FOREIGN KEY (JNO) REFERENCES J(JNO)
);
GO
/******************
三、插入数据
*******************/
--S表
INSERT INTO S(SNO,SNAME,STATUS,CITY) VALUES('S1','精益',20,'天津');
INSERT INTO S(SNO,SNAME,STATUS,CITY) VALUES('S2','盛锡',10,'北京');
INSERT INTO S(SNO,SNAME,STATUS,CITY) VALUES('S3','东方红',30,'北京');
INSERT INTO S(SNO,SNAME,STATUS,CITY) VALUES('S4','丰泰盛',20,'天津');
INSERT INTO S(SNO,SNAME,STATUS,CITY) VALUES('S5','为民',30,'上海');
--P表
INSERT INTO P(PNO,PNAME,COLOR,WEIGHT) VALUES('P1','螺母','红',12);
INSERT INTO P(PNO,PNAME,COLOR,WEIGHT) VALUES('P2','螺栓','绿',17);
INSERT INTO P(PNO,PNAME,COLOR,WEIGHT) VALUES('P3','螺丝刀','蓝',14);
INSERT INTO P(PNO,PNAME,COLOR,WEIGHT) VALUES('P4','螺丝刀','红',14);
INSERT INTO P(PNO,PNAME,COLOR,WEIGHT) VALUES('P5','凸轮','蓝',40);
INSERT INTO P(PNO,PNAME,COLOR,WEIGHT) VALUES('P6','齿轮','红',30);
--J表
INSERT INTO J(JNO,JNAME,CITY) VALUES('J1','三建','北京');
INSERT INTO J(JNO,JNAME,CITY) VALUES('J2','一汽','长春');
INSERT INTO J(JNO,JNAME,CITY) VALUES('J3','弹簧厂','天津');
INSERT INTO J(JNO,JNAME,CITY) VALUES('J4','造船厂','天津');
INSERT INTO J(JNO,JNAME,CITY) VALUES('J5','机车厂','唐山');
INSERT INTO J(JNO,JNAME,CITY) VALUES('J6','无线电厂','常州');
INSERT INTO J(JNO,JNAME,CITY) VALUES('J7','半导体厂','南京');
GO
--SPJ表
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S1','P1','J1',200);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S1','P1','J3',100);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S1','P1','J4',700);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S1','P2','J2',100);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S2','P3','J1',400);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S2','P3','J2',200);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S2','P3','J4',500);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S2','P3','J5',400);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S2','P5','J1',400);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S2','P5','J2',100);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S3','P1','J1',200);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S3','P3','J1',200);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S4','P5','J1',100);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S4','P6','J3',300);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S4','P6','J4',200);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S5','P2','J4',100);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S5','P3','J1',200);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S5','P6','J2',200);
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S5','P6','J4',500);
/******************
三、查询数据
*******************/
--1求供应工程J1零件的供应商号码SNO             DONE
SELECT DISTINCT SNO
FROM SPJ
WHERE JNO='J1'
--2求供应工程J1零件P1的供应商号码SNO           DONE
SELECT SNO
FROM SPJ
WHERE JNO='J1'AND PNO='P1'
--3求供应工程J1零件为红色的供应商号码SNO        DONE
SELECT DISTINCT SNO
FROM SPJ,P
WHERE SPJ.PNO=P.PNO AND P.COLOR='红' AND JNO='J1'
--4求没有使用天津供应商生产的红色零件的工程号JNO DONE
SELECT JNO
FROM J
WHERE JNO NOT IN(
	SELECT DISTINCT JNO
	FROM SPJ,S,P
	WHERE SPJ.SNO=S.SNO AND SPJ.PNO=P.PNO AND CITY='天津' AND COLOR='红'
)
--5求至少用了供应商S1所供应的全部零件的工程号JNO  DONE
SELECT DISTINCT JNO
FROM SPJ SPJX
WHERE NOT EXISTS(
	SELECT *
	FROM SPJ SPJY
	WHERE SPJY.SNO='S1' AND NOT EXISTS(
		SELECT *
		FROM SPJ SPJZ
		WHERE SPJZ.JNO=SPJX.JNO AND
				SPJZ.PNO=SPJY.PNO AND
				SPJZ.SNO=SPJY.SNO
	)
)
--1找出所有供应商的姓名和所在城市                 DONE
SELECT SNAME,CITY
FROM S
--2找出所有零件的名称、颜色、重量                 DONE
SELECT DISTINCT PNAME,COLOR,WEIGHT
FROM P
--3找出使用供应商S1所供应零件的工程号码           DONE
SELECT DISTINCT JNO
FROM SPJ
WHERE SNO='S1'
--4找出工程项目J2使用的各种零件的名称及其数量     DONE(TALK)
SELECT PNAME,SUM(QTY)QTY
FROM SPJ,P
WHERE SPJ.PNO=P.PNO AND JNO='J2'
GROUP BY PNAME

--5找出上海厂商供应的所有零件号码                 DONE
SELECT DISTINCT PNO
FROM SPJ,S
WHERE SPJ.SNO=S.SNO AND S.CITY='上海'
--6找出使用上海产的零件的工程名称                 DONE
SELECT DISTINCT JNAME
FROM SPJ,S,J
WHERE SPJ.SNO=S.SNO AND SPJ.JNO=J.JNO AND S.CITY='上海'
--7找出没有使用天津产的零件的工程号码             DONE
SELECT JNO
FROM J
WHERE JNO NOT IN(
	SELECT DISTINCT JNO
	FROM S,SPJ
	WHERE S.SNO=SPJ.SNO AND S.CITY='天津'  
) 
--8把全部红色零件的颜色改为蓝色
UPDATE P
SET COLOR='蓝'
WHERE COLOR='红'
--9由S5供给J4的零件P6改为由S3供应，请作必要的修改
UPDATE SPJ
SET SNO='S3'
WHERE SNO='S5' AND JNO='J4' AND PNO='P6'
--10从供应商关系中删除S2的记录，并从供应情况关系中删除相应的记录
DELETE
FROM SPJ
WHERE SNO='S2'
DELETE
FROM S
WHERE SNO='S2'
--11请将（S2，J6，P4，200）插入供应情况关系
INSERT INTO SPJ(SNO,PNO,JNO,QTY) VALUES('S2','P4','J6',200);


USE SPJ
GO

DROP TABLE SPJ
DROP TABLE S
DROP TABLE P
DROP TABLE J